import { IAlbum } from "./type";
import SpotLight from "../asset/Songs/Album/Spotlight.webp";
import Palette from "../asset/Songs/Album/Palette.webp";
import Makuake from "../asset/Songs/Album/Makuake.webp";
import Loveliekhate from "../asset/Songs/Album/Loveliekhate.webp";
import MyDreamBox from "../asset/Songs/Album/MyDreamBox.webp";
import Finale from "../asset/Songs/Album/finale.webp";

export const Album: IAlbum[] = [
  {
    image: MyDreamBox,
    url: "https://www.youtube.com/playlist?list=OLAK5uy_m1l9ig-Klycf65Zd9ibLSgYp4cfijmkLc",
    title: "my dream box",
    date: "2024. 10. 09.",
    songs: [
      "kakumei Zenya",
      "happy ever after",
      "Finale.",
      "Baby, with u",
      "77",
      "HIGHLIGHT",
      "happy ending",
      "BAE",
      "25",
      "WE ARE",
      "CHEAT LIFE (feat.punchnello)(prod. by GRAY)",
      "Pre-Romance",
      "Suki",
      "dream box",
    ],
  },

  {
    image: Palette,
    url: "https://www.youtube.com/playlist?list=OLAK5uy_k8A3ZrlYmlrgrd7GVUNYMbLPleO9EvLbk",
    title: "Palette",
    date: "2022. 02. 02.",
    songs: [
      "いけない baby",
      "ここで息をして",
      "23",
      "Palette",
      "hikari",
      "花のように",
      "プラスティック・ラブ",
      "ただのギャル",
      "honey-cage",
      "片っぽ - Acoustic Version",
      "letter…",
      "HARU",
    ],
  },
  {
    image: Finale,
    url: "https://www.youtube.com/playlist?list=OLAK5uy_lXbQqiCiFcpKG_Da6FxxhCDqR47TrvrSo",
    title: "プレロマンス/フィナーレ。",
    date: "2022. 09. 07.",
    songs: [
      "プレロマンス",
      "フィナーレ。",
      "片っぽ (Acoustic Version)",
      "プレロマンス (Instrumental)",
      "フィナーレ。 (Instrumental)",
    ],
  },
  {
    image: Loveliekhate,
    url: "https://www.youtube.com/playlist?list=OLAK5uy_nnzv5Tz01UJTeX50AKhdd-VVLajharqSc",
    title: "LOVE/LIKE/HATE",
    date: "2020. 11. 04.",
    songs: [
      "踊らせないで",
      "片っぽ",
      "Into your dream",
      "FAKE LOVE/",
      "Night D",
      "夢の続き",
      "2025",
      "SPOTLIGHT - Kan Inoue (WONK) Remix -",
      "with U",
    ],
  },
  {
    image: SpotLight,
    url: "https://www.youtube.com/watch?v=lNtaDHj5q8Q&list=OLAK5uy_mZ_rigFl8hAD250aZfcbHbjLdb_jHc2_w",
    title: "SPOTLIGHT",
    date: "2018. 10. 03.",
    songs: [
      "SPOTLIGHT",
      "この夜が明けるまで",
      "Fly me 2",
      "20",
      "Ma Boy",
      "((FULLMOON))",
      "Perfact love",
      "Succubus",
      "ONE LAST TIME (Prod.AmPm)",
      "Succubus feat.Kvi Baba (grooveman Spot Remix)",
      "20 Acoustic ver",
    ],
  },
  {
    image: Makuake,
    url: "https://www.youtube.com/playlist?list=OLAK5uy_mBl_4RCBovZPwXewplXB9vhDP7eEAlsws",
    title: "MAKUAKE",
    date: "2019. 11. 06.",
    songs: [
      "MAKUAKE",
      "FUTURE WAVE",
      "ONE feat. K.vsh",
      "HUSH",
      "hikari",
      "メタモルフォーゼ パラマジーノ",
      "shoujo",
      "初恋",
      "special girl",
      "HUSH-MONJOE Remix- feat. Kick a Show",
    ],
  },
];
